services:
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - 8000:8000
    networks:
      - ounwan
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    restart: always
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - ounwan

networks:
  ounwan:
    driver: bridge

volumes:
  db_data: {}
