services:
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - 3000:3000
    networks:
      - ounwan
    depends_on:
      - db
  db:
    image: mysql
    env_file:
      - .env
    restart: always
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - ounwan

networks:
  ounwan:
    driver: bridge

volumes:
  db_data: {}
